
CREATE ROLE role_admin INHERIT;
GRANT CREATE ON DATABASE tmmin_training_db TO role_admin;
GRANT CONNECT ON DATABASE tmmin_training_db TO role_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA istd TO role_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO role_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA hr TO role_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA sales TO role_admin;

CREATE ROLE user_admin_1 WITH LOGIN PASSWORD 'sulitditebak101' INHERIT;
GRANT role_admin TO user_admin_1;

-- ALTER ROLE user_admin_1 WITH INHERIT;
